version: "3.8"
services:
  new-api-project:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: foodics-service
    restart: unless-stopped
    ports:
      - ${APP_PORT}:${APP_INTERNAL_PORT:-2005}
    volumes:
      - .:/var/www/html
    networks:
      - default
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  default:
    name: ${NETWORK_NAME:-food_network}
    external: true
